---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: 889509784225.dkr.ecr.us-west-2.amazonaws.com/hello:1.0
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /
            port: 3001
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  ports:
  - port: 3003
    targetPort: 3001
    protocol: TCP
    name: hello
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "hello-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: hello
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: "hello-service"
              servicePort: 3003
